# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambientes',
            name='cantidades',
            field=models.IntegerField(default=0),
        ),
    ]
